apiVersion: v1
kind: Service
metadata:
  name: todo-fastapi-k8s-service
spec:
  selector:
    app: todo-fastapi-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
